# ------------------------------
# Gradle performance and memory
# ------------------------------
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# ------------------------------
# AndroidX + Jetifier support
# ------------------------------
android.useAndroidX=true
android.enableJetifier=true
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.suppressUnsupportedCompileSdk=34,35,36

# ------------------------------
# Flutter environment configuration
# ------------------------------
FLUTTER_ROOT=/Users/developer/flutter
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.flutter.sdk=/Users/yosrith/zanzoProjects/zanzo_frontend/android/flutterw

# ------------------------------
# Force Gradle to use JDK 17
# ------------------------------
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
